---
# runAsUser is the UID of the user to run the containers as in the ClusterTasks
# Optional.
#
# If given then all ClusterTasks created by this chart will be hard coded to run as this user.
# If 'rbacCreate' is also true then ClusterRole and SecurityContextConstraints will be created
# for this UID as well.
#
# If not given then all ClusterTasks created by this chart will run as whatever UID
# the Kubernetes platform they run on assigns them.
runAsUser: 1001

# rbacCreate if true and runAsUser is provided  then chart will create ClusterRole and
# SecurityContextConstraints for the given runAsUser UID, else if false then ClusterRole
# and SecurityContextConstraints will not be created even if runAsUser is specified leaving it
# to another process to create the appropriate RBAC resources.
rbacCreate: true

# imagePullPolicy is the impage pull policy to use for the ClusterTasks installed by this chart.
#
# NOTE
# ----
# This is a temporary parameter until See https://github.com/tektoncd/pipeline/issues/3423 is
# resolved and this parameter can be passed at runtime.
imagePullPolicy: IfNotPresent
