---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "tssc-workflow.eventListenerName" . }}
  labels:
    {{- include "tssc-workflow.labels" . | nindent 4 }}
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: gitea-pullreq
    template:
      name: {{ include "tssc-workflow.triggerTemplateName" . }}
