---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "tssc-workflow.eventListenerRouteName" .}}
  labels:
    {{- include "tssc-workflow.labels" . | nindent 4 }}
spec:
{{- if .Values.global.eventListenerRouteHost }}
  host: {{ .Values.global.eventListenerRouteHost }}
{{- end }}
  to:
    kind: Service
    name: {{ include "tssc-workflow.eventListenerServiceName" .}}
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
