{{- if and $.Values.rbacCreate $.Values.runAsUser -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tssc-workflow-tekton-cluster-resources.sccName" . }}
  labels:
    {{- include "tssc-workflow-tekton-cluster-resources.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ include "tssc-workflow-tekton-cluster-resources.sccName" . }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}
